### PR TITLE
Fix various build errors

### PR DESCRIPTION
**Pull request by ruslo**
I've added brief description of errors for each commit. Read them and let me know if something is not clear enough.

### CODE REVIEW

**Comment by ruslo** [comment]
@Dinno ping

**Comment by Dinno** [comment]
Have you made the list with your hands? Or do you use some checker? If so, then I should learn to use the checker myself.

**Comment by ruslo** [comment]
> Have you made the list with your hands?

List of what? Errors? No I've just run the build on Linux and OSX with shared/static variant of library.

**Comment by Dinno** [comment]
Sorry! This question was a result of my poor understanding of changes that you made. Now it is ok.

**Pull request merged**
